language: python
python:
  - "3.8"

env:
  - SECRET_KEY="SECRET_KEY123345"
  - DJANGO=1.8 DB=mysql

services:
  - mysql

install:
  - pipenv install
  - pip install -r requirements.txt

before_script:
  - mysql -e 'create database test;' -u root

script:
  - python src/manage.py test
