language: python
python:
  - "3.8"

env:
  - SECRET_KEY="SECRET_KEY123345"

services:
  - postgres

install:
  - pipenv install
  - pip install -r src/requirements.txt

script:
  - python src/manage.py test
