# Generated by Django 3.2.8 on 2021-11-07 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
